// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://nlhgorlanpqhgdcyqlzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5saGdvcmxhbnBxaGdkY3lxbHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MzM2NDgsImV4cCI6MjA1NzAwOTY0OH0.qjfiud--sAsq0foLP-HVCpglyX0Zk2Aatv8rG2TjH5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
);
